-- ==========================================
-- Supabase SQL Schema for Aarpoo Irroo Bookings
-- ==========================================
-- Run this script in your Supabase SQL Editor:
-- 1. Go to https://app.supabase.com/ project dashboard
-- 2. Click "SQL Editor" in the left navigation
-- 3. Paste this script and click "Run"

CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id VARCHAR(50) NOT NULL UNIQUE,
    order_id VARCHAR(100) NOT NULL,
    payment_id VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    seats INT DEFAULT 1,
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Allow serverless backend (service_role key) full access to insert & read bookings
CREATE POLICY "Allow service role full access" ON public.bookings
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bookings_booking_id ON public.bookings (booking_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_email ON public.bookings (customer_email);
CREATE INDEX IF NOT EXISTS idx_bookings_payment_id ON public.bookings (payment_id);
