-- ==========================================
-- Supabase SQL Schema for Aarpoo Irroo Platform
-- ==========================================
-- Run this script in your Supabase SQL Editor:
-- 1. Go to https://app.supabase.com/ project dashboard
-- 2. Click "SQL Editor" in the left navigation
-- 3. Paste this script and click "Run"

-- 1. Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id VARCHAR(50) NOT NULL UNIQUE,
    order_id VARCHAR(100) NOT NULL,
    payment_id VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    seats INT DEFAULT 1,
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Partner Proposals Table
CREATE TABLE IF NOT EXISTS public.partner_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(255),
    contact_person VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    partner_type VARCHAR(100),
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. General Contact Messages Table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow serverless backend (service_role key) full access
CREATE POLICY "Allow service role full access to bookings" ON public.bookings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service role full access to partner_inquiries" ON public.partner_inquiries FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service role full access to contact_messages" ON public.contact_messages FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_bookings_booking_id ON public.bookings (booking_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_email ON public.bookings (customer_email);
CREATE INDEX IF NOT EXISTS idx_partner_email ON public.partner_inquiries (email);
CREATE INDEX IF NOT EXISTS idx_contact_email ON public.contact_messages (email);
